### ISSUE TITLE
[Question] Sudo signature broken? on kernel v3

### ISSUE THREAD

**Issue by KONFeature** [zerodevapp/sdk#119]
Here, the signature is concat with the current validator identifier:
https://github.com/zerodevapp/sdk/blob/14acdc1b0596368e4ce0b973b0fd5d91ad74a4f3/packages/core/accounts/kernel/createKernelAccount.ts#L421

But, even if in Sudo mode, the `pluginManager` append the `validator.identifier` to the validatorId here: https://github.com/zerodevapp/sdk/blob/14acdc1b0596368e4ce0b973b0fd5d91ad74a4f3/packages/core/accounts/utils/toKernelPluginManager.ts#L190

Thus, it won't work in sudo mode, because when the sig is extracted here: [Validation type lib](https://github.com/zerodevapp/kernel/blob/b8442f2b138b7832b2353b564bcdebb269446a46/src/utils/ValidationTypeLib.sol#L80) ([called here](https://github.com/zerodevapp/kernel/blob/b8442f2b138b7832b2353b564bcdebb269446a46/src/Kernel.sol#L274)), it only offset one byte (for the sudo mode), and not 21 bytes (what's done in the SDK, mode + identifier, often being the address)

**Comment by SahilVasava** [comment]
Agree [this](https://github.com/zerodevapp/kernel/blob/b8442f2b138b7832b2353b564bcdebb269446a46/src/Kernel.sol#L274-L276) is not being executed when verifying signature with SUDO validator.

But currently the validationId in case of SUDO validator (non-permission validator) as well will be `0x01+[SUDO_VALIDATOR_ADDRESS]` which is same as [vId](https://github.com/zerodevapp/kernel/blob/b8442f2b138b7832b2353b564bcdebb269446a46/src/Kernel.sol#L275C19-L275C35) stored in storage for sudo validator.
So the flow works as expected. 

There doesn't seems to be any security issue because of that.

I agree though the `getIdentifier` flow in SDK is bit confusing. Will try to modify that.
